spring:
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/ies
        username: root
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
      mail:
        host: smtp.gmail.com
        password: wmndytkkalvwwqqe
        port: 587
        properties:
            mail:
              smtp:
                auth: true
                starttls:
                  enable: true
        username: shribinwade.100@gmail.com

